import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import BotonAtomico from "@/components/atoms/boton";
import { useEffect, useState } from "react";
import ChecklistItem from "@/components/atoms/checklistitem";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const [textoDinamico, setTextoDinamico] = useState("");
  const [lista, setLista] = useState<{ id: number; texto: string; completada: boolean }[]>([]);

  const actualizar = (event: React.ChangeEvent<HTMLInputElement>) => {
    setTextoDinamico(event.currentTarget.value);
  };

  const AgregarTarea = () => {
    if (textoDinamico.trim()) {
      const nuevaTarea = {
        id: Date.now(),
        texto: textoDinamico,
        completada: false,
      };
      setLista([...lista, nuevaTarea]);
      localStorage.setItem("listaTareas", JSON.stringify(lista));
      setTextoDinamico("");
    }
  };

   useEffect(() => {
    const listaGuardada = localStorage.getItem("listaTareas");
    if (listaGuardada) {
      setLista(JSON.parse(listaGuardada)); // Convierte el string a array
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("listaTareas", JSON.stringify(lista));
  }, [lista]);

  const toggleItem = (id: number) => {
    const nuevaLista = lista.map((item) =>
      item.id === id ? { ...item, completada: !item.completada } : item
    );
    setLista(nuevaLista);
  };

  const VaciarLista = () => {
    setLista([]);
  };

  const borrarCompletadas = () => {
    const sincompletar = lista.filter((item) => !item.completada);
    setLista(sincompletar);
  };

  return (
    <>
      <Head>
        <title>TO DO LIST</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <center>
        <h1>{textoDinamico}</h1>

        <div style={{ minHeight: "100vh" }}>
          <div className="divMedio">
            <h1>--- TO DO LIST ---</h1>
            <input
              className="inStyle"
              type="text"
              placeholder="Crea una tarea..."
              value={textoDinamico}
              onChange={actualizar}
            />
            <button className="btStyle" onClick={AgregarTarea}>
              Crear Tarea
            </button>
            <button className="btStyle2" onClick={borrarCompletadas}>
              Eliminar Completadas
            </button>
            <button className="btStyle2" onClick={VaciarLista}>
              Eliminar Todos
            </button>
            <ul>
              {lista.map((item) => (
                <li style={{ listStyleType: 'none' }} key={item.id}>
                  <ChecklistItem
                    id={item.id}
                    texto={item.texto}
                    completada={item.completada}
                    onToggle={toggleItem}
                  />
                </li>
              ))}
            </ul>
            <h3>Mirar abajo de la pagina</h3>
          </div>
        </div>
        <div className="divImg">
            <h3> YO </h3>
        </div>
      </center>
    </>
  );
}
